title: Road to RCE
twitter: systemDumb
permalink: /:title
url: "https://AustinCundiff.github.io"
author: "Austin Cundiff"
markdown: kramdown
header_page_refs: ['about', 'contact']
github_username: "AustinCundiff"
twitter:
  username: systemDumb
cayman-blog:
  date_format: "%b %-d, %Y"
theme:
plugins:
  - jekyll-target-blank
