title: Road to RCE
#theme: jekyll-theme-tactile
twitter_username: systemDumb
permalink: /:title
url: "https://AustinCundiff.github.io"
author: "Austin Cundiff"
markdown: kramdown
# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
twitter_username: "@systemDumb"
github_username: "AustinCundiff"

footer-links:
  - twitter: systemDumb
  - linkedin: austin-cundiff-7b015811a
 
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme
 
remote_theme: pages-themes/cayman@v0.2.0
