title: Road to RCE
twitter: systemDumb
permalink: /:title
url: "https://AustinCundiff.github.io"
author: "Austin Cundiff"
markdown: kramdown
header_page_refs: ['about', 'contact']
github_username: "AustinCundiff"
twitter:
  username: systemDumb
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
